vim.deprecate = function() end
require "user.plugins"
require "user.options"
require "user.null"
require "user.cmp"
require "user.lsp"
require "user.snippets"
require "user.treesitter"
require "user.telescope"
require "user.neovide"
require "user.keymaps"
require "user.diffview"
require "user.git"
require "user.noice"
require "user.copilot"
require "user.mini"
