--require('lualine').setup({
--    options = {
--        icons_enabled = false,
--        section_separators = { left = '', right = '' },
--        component_separators = { left = '', right = '' }
--    },
--    sections = {
--        lualine_a = { 'mode' },
--        lualine_b = { 'branch' },
--        lualine_c = { { 'filename', path = 1 } },
--        lualine_x = { 'encoding', 'fileformat', 'filetype' },
--        lualine_y = { 'progress' },
--        lualine_z = { 'location' }
--    },
--}
--)
--require("bufferline").setup {
--    options = {
--        mode = "buffers", -- set to "tabs" to only show tabpages instead
--        themable = true,
--        numbers = "none",
--        close_command = "bdelete! %d",       -- can be a string | function, | false see "Mouse actions"
--        right_mouse_command = "bdelete! %d", -- can be a string | function | false, see "Mouse actions"
--        left_mouse_command = "buffer %d",    -- can be a string | function, | false see "Mouse actions"
--        middle_mouse_command = nil,          -- can be a string | function, | false see "Mouse actions"
--        indicator = {
--            style = "underline"
--        },
--        buffer_close_icon = '',
--        modified_icon = '●',
--        close_icon = '',
--        left_trunc_marker = '',
--        right_trunc_marker = '',
--        max_name_length = 10,
--        max_prefix_length = 7, -- prefix used when a buffer is de-duplicated
--        truncate_names = true, -- whether or not tab names should be truncated
--        tab_size = 10,
--        diagnostics = "nvim_lsp",
--        diagnostics_update_on_event = true, -- use nvim's diagnostic handler
--        color_icons = false,                -- whether or not to add the filetype icon highlights
--        show_buffer_icons = true,
--        show_buffer_close_icons = true,
--        show_close_icon = true,
--        show_tab_indicators = true,
--        show_duplicate_prefix = true,
--        duplicates_across_groups = true, -- whether to consider duplicate paths in different groups as duplicates
--        persist_buffer_sort = true,      -- whether or not custom sorted buffers should persist
--        -- can also be a table containing 2 custom separators
--        -- [focused and unfocused]. eg: { '|', '|' }
--        separator_style = "thick",
--        auto_toggle_bufferline = true,
--        hover = {
--            enabled = true,
--            delay = 200,
--            reveal = { 'close' }
--        },
--    },
--    highlights = {
--        buffer_selected = {
--            bg = 'orange',
--            bold = true,
--        },
--    }
--}
--
